# Generated by Django 3.2.7 on 2021-10-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='available',
            new_name='projector_available',
        ),
    ]
