# Generated by Django 3.2.7 on 2021-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_booking', '0002_auto_20211013_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
